name: contact_finder
description: A new flutter plugin project.
version: 0.0.1
author: Conrad Heidebrecht <chipthinkstudios@gmail.com>
homepage: https://github.com/eternali/contact_finder

environment:
  sdk: ">= 1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.contactfinder
    pluginClass: ContactFinderPlugin
